### ISSUE TITLE
全局无法生效

### ISSUE THREAD

**Issue by AquamarineCyan** [kexue-z/nonebot-plugin-word-bank2#10]
全局指令无法生效，目前解决方式是关掉bot，手动在json改为"0"重启才生效

**Comment by kexue-z** [comment]
看看指令怎么发的
然后再看看怎么存的

**Comment by kexue-z** [comment]
下版本在nb beta2上一切正常
```
name         : nonebot-plugin-word-bank2
version      : 0.1.3.2
description  : 无数据问答插件

dependencies
 - aiofiles >=0.8.0,<0.9.0
 - httpx >=0.18.0,<1.0.0
 - nonebot-adapter-onebot >=2.0.0-beta.1,<=2.0.0-beta.2
 - nonebot2 >=2.0.0-beta.1,<=2.0.0-beta.2
 ```

**Comment by AquamarineCyan** [comment]
![QQ图片20220310204242](https://user-images.githubusercontent.com/64363680/157664256-e8bc2bd4-a0ff-42a0-8033-1df3b54afb7f.png)
![QQ图片20220310204258](https://user-images.githubusercontent.com/64363680/157664266-6bcbd9eb-3f2f-4791-a6cb-3336fd9b383c.png)
word-bank2:0.1.3.2
nonebot2.b2

**Comment by AquamarineCyan** [comment]
> ![QQ图片20220310204242](https://user-images.githubusercontent.com/64363680/157664256-e8bc2bd4-a0ff-42a0-8033-1df3b54afb7f.png) ![QQ图片20220310204258](https://user-images.githubusercontent.com/64363680/157664266-6bcbd9eb-3f2f-4791-a6cb-3336fd9b383c.png) word-bank2:0.1.3.2 nonebot2.b2

"congruence": {
        "0": {},
        "private_1057424730": {
            "1": [
                "2"
            ]
        }
    },

**Comment by kexue-z** [comment]
看看nb的log 是否有报错 是否命中`matcher` 
并且留下你的`bank.json` 文件

**Comment by AquamarineCyan** [comment]
03-10 20:58:05 [SUCCESS] nonebot | ONEBOT V11 2799364859 | [message.private.friend]: Message -1660718896 from 1057424730 "全局问1答2"
03-10 20:58:11 [DEBUG] nonebot | Checking for matchers in priority 1...
03-10 20:58:11 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored
03-10 20:58:11 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored
03-10 20:58:11 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored
03-10 20:58:11 [DEBUG] nonebot | Checking for matchers in priority 5...
03-10 20:58:11 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored
03-10 20:58:11 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored
03-10 20:58:11 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored
03-10 20:58:11 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored
03-10 20:58:11 [DEBUG] nonebot | Checking for matchers in priority 10...
03-10 20:58:11 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored
03-10 20:58:11 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored
03-10 20:58:11 [DEBUG] nonebot | Checking for matchers in priority 11...
03-10 20:58:11 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored
03-10 20:58:11 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored
03-10 20:58:11 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored
03-10 20:58:11 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored
03-10 20:58:11 [DEBUG] nonebot | Checking for matchers in priority 15...
03-10 20:58:11 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored
03-10 20:58:11 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored
03-10 20:58:11 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored
03-10 20:58:11 [DEBUG] nonebot | Checking for matchers in priority 99...
03-10 20:58:11 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_word_bank2, type=message, priority=99, temp=False>
03-10 20:58:11 [DEBUG] nonebot | Running matcher <Matcher from nonebot_plugin_word_bank2, type=message, priority=99, temp=False>
03-10 20:58:11 [DEBUG] nonebot | Running handler <Dependent call=<function handle_wb at 0x00000166CA2A7CA0>, params=[ModelField(name='event', type=MessageEvent, required=True)], parameterless=[]>
03-10 20:58:11 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_word_bank2, type=message, priority=99, temp=False> running complete

**Comment by kexue-z** [comment]
哦， 全局需要设置超级管理员

**Comment by AquamarineCyan** [comment]
.env中需要添加什么指令

**Comment by kexue-z** [comment]
https://v2.nonebot.dev/docs/tutorial/configuration#superusers
