### ISSUE TITLE
添加问题不回复BUG

### ISSUE THREAD

**Issue by 741807012** [kexue-z/nonebot-plugin-word-bank2#13]
问
你好
答
{不好}

格式是这样的，有{}就不会回复了

**Comment by kexue-z** [comment]
因为。。。 `{不好}` 被 formmat 了 导致了 keyerror
跟 
```py
"{不好}".format(不好="不好")
```
一样道理

建议能不用 `{}` 就不用

**Comment by kexue-z** [comment]
逝世
```
问
你好
答
{{不好}}
```

**Comment by 741807012** [comment]
> 因为。。。 `{不好}` 被 formmat 了 导致了 keyerror 跟
> 
> ```python
> "{不好}".format(不好="不好")
> ```
> 
> 一样道理
> 
> 建议能不用 `{}` 就不用

就是必须要所以才反馈的

**Comment by 741807012** [comment]
需要这样的回答

**Comment by kexue-z** [comment]
发版了 `0.1.4.2`
