### ISSUE TITLE
正则匹配问题

### ISSUE THREAD

**Issue by HiyoriTUK** [kexue-z/nonebot-plugin-word-bank2#14]
![image](https://user-images.githubusercontent.com/45660358/166503868-98744607-c65f-45dd-a123-fd344a675031.png)
即使按照readme中的示例也无法正确识别

**Comment by HiyoriTUK** [comment]
控制台中中括号回变成这样
![image](https://user-images.githubusercontent.com/45660358/166504874-c37f2bbc-536d-4470-ac4f-b5e3be9409bf.png)

**Comment by kexue-z** [comment]
看看 `bank.json`

**Comment by HiyoriTUK** [comment]
> 看看 `bank.json`

![image](https://user-images.githubusercontent.com/45660358/166505260-05927299-baf3-45ce-b258-355d44439939.png)

**Comment by HiyoriTUK** [comment]
> 是在regex分类里吗

是

**Comment by kexue-z** [comment]
有空再修（
