### ISSUE TITLE
正则问答失灵 bot发癫（

### ISSUE THREAD

**Issue by dreamsate1** [kexue-z/nonebot-plugin-word-bank2#21]
示例：群友正则问@bot 答一个图片时
然后接下来只要群友发表情包 图片 语音 bot都会回复这个图片
![SA5~%06FUD5$}BN92YA{N8B](https://user-images.githubusercontent.com/64997828/175996124-adc3d63a-3025-42d0-a17c-8ad44b34cee8.jpg)

**Comment by dreamsate1** [comment]
貌似无法删除这个词库  
有办法解决吗呜呜呜

**Comment by kexue-z** [comment]
看看词库的json是什么

**Comment by RafuiiChan** [comment]
> 貌似无法删除这个词库 有办法解决吗呜呜呜

猜这是at机器人的消息被解析成空了，所以教进去的匹配的正则表达式就是个 "" 

找到词库的json文件正则问答词库部分，然后删掉空的那个，或者改一下那个空的关键词

**Comment by dreamsate1** [comment]
![4HWBJJRGX62LO ~8TVPJ 9V](https://user-images.githubusercontent.com/64997828/176097324-bacb03a3-dd96-47bf-98ff-bd1d0e7a211a.jpg)
