### ISSUE TITLE
可以回答小程序链接吗

### ISSUE THREAD

**Issue by jinxx52** [kexue-z/nonebot-plugin-word-bank2#25]
微信公众号文章之类的只能转发，没办法复制或者是没办法在一个对话框内打出问答指令的

**Comment by jinxx52** [comment]
似乎可以直接回答链接 但是不太美观的样子 。。

**Comment by kexue-z** [comment]
不能小程序 只能链接 如果不美观可以转短链接

**Comment by jinxx52** [comment]
> 不能小程序 只能链接 如果不美观可以转短链接

短链接也可行 谢谢
