### ISSUE TITLE
遇到报错

### ISSUE THREAD

**Issue by hatoriss** [kexue-z/nonebot-plugin-word-bank2#27]
首先很感谢作者写了这个插件！但是使用的时候遇到了问题如下，操作系统是centos，安装途径是pip（安装的时候没有报错之类的问题）已经尝试了重新下载但是没有解决，在win10中未遇到此问题。
![798de77533e8941_edit_626161684613308](https://user-images.githubusercontent.com/110772966/183969439-ac467e21-ae7f-40a5-8382-4a6213943a28.png)

**Comment by kexue-z** [comment]
参数不够 不能直接用
超管用
查询群xxxx词库

**Comment by hatoriss** [comment]
已知我大号是超管，大号使用查询群xxxx词库命令没有回复……查询个人词库也不行，日志显示也仿佛没这条命令一样没下文甚至没有报错，这个会是哪里出问题了😭

**Comment by kexue-z** [comment]
`^查询\s*((?:群|用户)*)\s*(\d*)\s*((?:全局)?(?:模糊|正则)?@?)\s*词库\s*(.*?)\s*$`

对着正则 我忘了（

**Comment by hatoriss** [comment]
现在各种问法都试过了，还是没有返回……重启了bot依旧如此

**Comment by hatoriss** [comment]
已解决，居然是版本问题……
