### ISSUE TITLE
是否有查询所有问答的命令？

### ISSUE THREAD

**Issue by mmmjie** [kexue-z/nonebot-plugin-word-bank2#28]
目前似乎需要分开查询？
查询词库
查询模糊词库
查询正则词库
查询@词库
 然后还要区分全局

如果加多了，有时候想找一个删除，还得试好多次。

**Comment by kexue-z** [comment]
那为什么不直接去读json对着改呢😥

**Comment by mmmjie** [comment]
> 那为什么不直接去读json对着改呢😥

因为有给其他群用，并不是只有我自己一个人用

**Comment by mmmjie** [comment]
想了想，这属于自己的需求，我还是关闭好了，不好啥意思。。

**Comment by kexue-z** [comment]
那就直接 查询词库 就好了 
正则模糊全匹配是不同的
发3次查3种
这样有助于分类捏
