### ISSUE TITLE
Failed to import

### ISSUE THREAD

**Issue by Danwk2333** [kexue-z/nonebot-plugin-word-bank2#32]
![D7)CQ1`))15}QD96JJ~RP5H](https://user-images.githubusercontent.com/106854600/195522817-495125a7-7c0c-47ac-8809-074a0d5eecfd.png)

**Comment by Yonnemy2nd** [comment]
似乎是nonebot版本更新了，这个的代码没更新导致的

**Comment by 19231224lhr** [comment]
您好，最后怎么解决的啊

**Comment by kexue-z** [comment]
更新最新版`0.1.6`

**Comment by 19231224lhr** [comment]
好的，谢谢大佬



---Original---
From: ***@***.***&gt;
Date: Wed, Oct 26, 2022 18:13 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kexue-z/nonebot-plugin-word-bank2] Failed to import (Issue #32)




 
更新最新版0.1.6
