### ISSUE TITLE
我不会设置词条

### ISSUE THREAD

**Issue by xhs6666** [kexue-z/nonebot-plugin-word-bank2#35]
我不知道是直接发消息来设置词条
![W)MCKUC( MQUP 0@68C{S(N](https://user-images.githubusercontent.com/100497017/201263389-b1c7b1a2-ae02-4bff-9eed-9b1d61737bde.png)
还是在词库里加

**Comment by xhs6666** [comment]
发消息没反应

**Comment by kexue-z** [comment]
/ 去了
