### ISSUE TITLE
群友设全局，转发给超管审核

### ISSUE THREAD

**Issue by MoKeNeng** [kexue-z/nonebot-plugin-word-bank2#40]
当群友想要添加全局词库时，机器人转发消息词库+回答内容给超管，超管”ok“通过，即可添加，"no"则驳回。

**Comment by kexue-z** [comment]
那不如直接给他超管

**Comment by MoKeNeng** [comment]
我已经将源代码改成了所有人都可以添加到同一个里词库，现在能不能搞个新功能让超管审核并修改他们添加的内容。
