### ISSUE TITLE
请问该插件可以做的更加功能完善,操作简洁么

### ISSUE THREAD

**Issue by YouYouLip** [kexue-z/nonebot-plugin-word-bank2#41]
我感觉这个自定义词库蛮好的 就是吧操作上可能不方便 需要模糊/全匹配/正则@问 答 这种形式 nonebot商店机器人模块里ATRI那个自定义词库我觉得很容易上手方便简单（主要是群友脑子不太ok 不是很会）内个的形式是先触发关键词 然后bot会问你要教什么 打上内容之后再会要求答什么 然后就是选择模式 正则/模糊/全匹配 而且还可以用逗号隔开来表示多回复内容 我希望作者可以做成类似这样的 主要是我想把ATRI里面的那个自定义回复套出来 结果发现是一圈套一圈的 根本单独套不出来

希望作者可以做成这样 如果能力有限或者不想考虑也没问题 这种也可以用 只是自我感觉可能会比较麻烦一点

**Comment by kexue-z** [comment]
发生什么事情了
