### ISSUE TITLE
删除词条可不可以支持词库中其他指向的一条

### ISSUE THREAD

**Issue by YouYouLip** [kexue-z/nonebot-plugin-word-bank2#42]
如题 就是好比如词库问句是摸 但是摸有好几条 指向其中一条删除可以么

**Comment by YouYouLip** [comment]
另外可以将词库中的你改为触发者么 就是答句里面有你，把你改成触发者的名字或者at形式

**Comment by kexue-z** [comment]
诶？

**Comment by YouYouLip** [comment]
> 诶？

是我说的模糊吗（悲）我意思是好比如有个问xxxx答1111这种形式的问答 但是问xxxx有好几个回复 想删掉其中一个回复貌似做不到 只能删除所有回复（？）

**Comment by kexue-z** [comment]
是这个问题 wb3会解决的（咕
