### ISSUE TITLE
可以更改使用权限吗？

### ISSUE THREAD

**Issue by lihuan544826** [kexue-z/nonebot-plugin-word-bank2#46]
比如群主或者群管理可以全局添加词条。

**Comment by kexue-z** [comment]
你可以把他添加为超管。否则修改权限仅限于本群内。

**Comment by lihuan544826** [comment]
但是我不想让别人拥有可以删除词条的功能怎么做到呢，请问配置文件里没有更改权限的词条吗~

**Comment by kexue-z** [comment]
没有喵。你可以手动改改代码。

https://github.com/kexue-z/nonebot-plugin-word-bank2/blob/5767114e4186416d4239d3c44af6f086e5acf9c0/nonebot_plugin_word_bank2/__init__.py#L125

而且这个是正则里面写好的，也要重新组织一下才可以。

**Comment by lihuan544826** [comment]
好的~谢谢~
