### ISSUE TITLE
关于英文大小写

### ISSUE THREAD

**Issue by lihuan544826** [kexue-z/nonebot-plugin-word-bank2#47]
请问是否有开关可以让机器人忽略大小写呢~？现在输入类似这种指令

**Comment by kexue-z** [comment]
正则匹配的规则。

https://github.com/kexue-z/nonebot-plugin-word-bank2/blob/5767114e4186416d4239d3c44af6f086e5acf9c0/nonebot_plugin_word_bank2/word_entry.py#L68

改这个应该能行

**Comment by lihuan544826** [comment]
return bool(re.search(_key, _msg, re.S|re.I))
请问，68行我改成这样之后插件还是忽略大小写无效~应该怎么改~

**Comment by lihuan544826** [comment]
已解决，感谢作者~
