### ISSUE TITLE
关于使用时发现的匹配 bug 如下

### ISSUE THREAD

**Issue by Astolfocat** [kexue-z/nonebot-plugin-word-bank2#5]
使用以下命令：
全局模糊@问 rua 答 图片A
bot 回复记住并且记入 json 里
在群聊如下发送消息：
@bot rua一下
bot 成功回答 图片A
但是在群聊如下发送消息：
@bot XXXrua一下
bot 无法模糊匹配到命令，即 bot 无法匹配到不以问句开头的消息

**Comment by MeetWq** [comment]
雀食有问题，我的锅，我有空改一下
