### ISSUE TITLE
图片回复失效

### ISSUE THREAD

**Issue by BalconyJH** [kexue-z/nonebot-plugin-word-bank2#7]
**环境信息**

nb2版本：2.0.0b1
运行环境：winserver2019
go-cqhttp 版本：1.0.0b8f2

**Bug 描述**

描述你遇到的问题：图片回复失效

**报错日志**

```
02-15 20:12:33 [SUCCESS] nonebot | ONEBOT V11 3313443581 | [message.private.friend]: Message -1750460939 from 1091276703 "问1答[CQ:image,file=e4f0cdcdad4b625d5f1c5e1f20b68626.image,url=https://c2cpicdw.qpic.cn/offpic_new/0/1091276703-2663398180-E4F0CDCDAD4B625D5F1C5E1F20B68626/0?term=3]"
02-15 20:12:33 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_word_bank2, type=message, priority=1, temp=False>
02-15 20:12:34 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_word_bank2, type=message, priority=1, temp=False> running complete
02-15 20:12:41 [SUCCESS] nonebot | ONEBOT V11 3313443581 | [message.private.friend]: Message -1865952788 from 1091276703 "1"
02-15 20:12:41 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_word_bank2, type=message, priority=99, temp=False>
02-15 20:12:41 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_word_bank2, type=message, priority=99, temp=False> running complete
02-15 20:12:41 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_word_bank2, type=message, priority=99, temp=False> failed.
Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\programdata\miniconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "c:\programdata\miniconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "c:\programdata\miniconda3\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\programdata\miniconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\programdata\miniconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "c:\programdata\miniconda3\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "c:\programdata\miniconda3\lib\site-packages\nb_cli\handlers\deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "c:\programdata\miniconda3\lib\site-packages\nonebot\__init__.py", line 300, in run
    get_driver().run(*args, **kwargs)
  File "c:\programdata\miniconda3\lib\site-packages\nonebot\drivers\fastapi.py", line 232, in run
    uvicorn.run(
  File "c:\programdata\miniconda3\lib\site-packages\uvicorn\main.py", line 447, in run
    server.run()
  File "c:\programdata\miniconda3\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\programdata\miniconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\programdata\miniconda3\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "c:\programdata\miniconda3\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\programdata\miniconda3\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "c:\programdata\miniconda3\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "c:\programdata\miniconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\programdata\miniconda3\lib\site-packages\nonebot\message.py", line 158, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "c:\programdata\miniconda3\lib\site-packages\nonebot\message.py", line 207, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "c:\programdata\miniconda3\lib\site-packages\nonebot\matcher.py", line 742, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "c:\programdata\miniconda3\lib\site-packages\nonebot\matcher.py", line 709, in simple_run
    await handler(
  File "c:\programdata\miniconda3\lib\site-packages\nonebot\dependencies\__init__.py", line 76, in __call__
    return await self.call(**values)
  File "c:\programdata\miniconda3\lib\site-packages\nonebot_plugin_word_bank2\__init__.py", line 53, in handle_wb
    await wb.parse_msg(
  File "c:\programdata\miniconda3\lib\site-packages\nonebot_plugin_word_bank2\data_source.py", line 226, in parse_msg
    return Message.template(msg).format(*file_list, **at, **kwargs)
  File "c:\programdata\miniconda3\lib\site-packages\nonebot\adapters\_template.py", line 80, in format
    msg += self.vformat(self.template, args, kwargs)
  File "c:\programdata\miniconda3\lib\site-packages\nonebot\adapters\_template.py", line 94, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "c:\programdata\miniconda3\lib\site-packages\nonebot\adapters\_template.py", line 165, in _vformat
    formatted_text = self.format_field(obj, str(format_control))
  File "c:\programdata\miniconda3\lib\site-packages\nonebot\adapters\_template.py", line 181, in format_field
    super().format_field(value, format_spec)
  File "c:\programdata\miniconda3\lib\string.py", line 235, in format_field
    return format(value, format_spec)
TypeError: unsupported format string passed to bytes.__format__
```

**Comment by kexue-z** [comment]
看 文 档

--------------原始邮件--------------
发件人："BalconyJH ***@***.***&gt;;
发送时间：2022年2月15日(星期二) 晚上8:29
收件人："kexue-z/nonebot-plugin-word-bank2" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[kexue-z/nonebot-plugin-word-bank2] 图片回复失效 (Issue #7)
-----------------------------------

 

 
环境信息
 
nb2版本：2.0.0b1
 运行环境：winserver2019
 go-cqhttp 版本：1.0.0b8f2
 
Bug 描述
 
描述你遇到的问题：图片回复失效
 
报错日志
 02-15 20:12:33 [SUCCESS] nonebot | ONEBOT V11 3313443581 | [message.private.friend]: Message -1750460939 from 1091276703 "问1答[CQ:image,file=e4f0cdcdad4b625d5f1c5e1f20b68626.image,url=https://c2cpicdw.qpic.cn/offpic_new/0/1091276703-2663398180-E4F0CDCDAD4B625D5F1C5E1F20B68626/0?term=3]" 02-15 20:12:33 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_word_bank2, type=message, priority=1, temp=False&gt; 02-15 20:12:34 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_word_bank2, type=message, priority=1, temp=False&gt; running complete 02-15 20:12:41 [SUCCESS] nonebot | ONEBOT V11 3313443581 | [message.private.friend]: Message -1865952788 from 1091276703 "1" 02-15 20:12:41 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_word_bank2, type=message, priority=99, temp=False&gt; 02-15 20:12:41 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_word_bank2, type=message, priority=99, temp=False&gt; running complete 02-15 20:12:41 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_word_bank2, type=message, priority=99, temp=False&gt; failed. Traceback (most recent call last):   File "c:\programdata\miniconda3\lib\runpy.py", line 197, in _run_module_as_main     return _run_code(code, main_globals, None,   File "c:\programdata\miniconda3\lib\runpy.py", line 87, in _run_code     exec(code, run_globals)   File "C:\ProgramData\Miniconda3\Scripts\nb.exe\__main__.py", line 7, in <module&gt;     sys.exit(main())   File "c:\programdata\miniconda3\lib\site-packages\click\core.py", line 1128, in __call__     return self.main(*args, **kwargs)   File "c:\programdata\miniconda3\lib\site-packages\click\core.py", line 1053, in main     rv = self.invoke(ctx)   File "c:\programdata\miniconda3\lib\site-packages\click\core.py", line 1659, in invoke     return _process_result(sub_ctx.command.invoke(sub_ctx))   File "c:\programdata\miniconda3\lib\site-packages\click\core.py", line 1395, in invoke     return ctx.invoke(self.callback, **ctx.params)   File "c:\programdata\miniconda3\lib\site-packages\click\core.py", line 754, in invoke     return __callback(*args, **kwargs)   File "c:\programdata\miniconda3\lib\site-packages\nb_cli\commands\main.py", line 30, in run     run_bot(file, app)   File "c:\programdata\miniconda3\lib\site-packages\nb_cli\handlers\deploy.py", line 24, in run_bot     nonebot.run(app=f"{module_name}:{app}")   File "c:\programdata\miniconda3\lib\site-packages\nonebot\__init__.py", line 300, in run     get_driver().run(*args, **kwargs)   File "c:\programdata\miniconda3\lib\site-packages\nonebot\drivers\fastapi.py", line 232, in run     uvicorn.run(   File "c:\programdata\miniconda3\lib\site-packages\uvicorn\main.py", line 447, in run     server.run()   File "c:\programdata\miniconda3\lib\site-packages\uvicorn\server.py", line 68, in run     return asyncio.run(self.serve(sockets=sockets))   File "c:\programdata\miniconda3\lib\asyncio\runners.py", line 44, in run     return loop.run_until_complete(main)   File "c:\programdata\miniconda3\lib\asyncio\base_events.py", line 629, in run_until_complete     self.run_forever()   File "c:\programdata\miniconda3\lib\asyncio\windows_events.py", line 316, in run_forever     super().run_forever()   File "c:\programdata\miniconda3\lib\asyncio\base_events.py", line 596, in run_forever     self._run_once()   File "c:\programdata\miniconda3\lib\asyncio\base_events.py", line 1890, in _run_once     handle._run()   File "c:\programdata\miniconda3\lib\asyncio\events.py", line 80, in _run     self._context.run(self._callback, *self._args)   File "c:\programdata\miniconda3\lib\site-packages\nonebot\message.py", line 158, in _check_matcher     await _run_matcher(Matcher, bot, event, state, stack, dependency_cache) &gt; File "c:\programdata\miniconda3\lib\site-packages\nonebot\message.py", line 207, in _run_matcher     await matcher.run(bot, event, state, stack, dependency_cache)   File "c:\programdata\miniconda3\lib\site-packages\nonebot\matcher.py", line 742, in run     await self.simple_run(bot, event, state, stack, dependency_cache)   File "c:\programdata\miniconda3\lib\site-packages\nonebot\matcher.py", line 709, in simple_run     await handler(   File "c:\programdata\miniconda3\lib\site-packages\nonebot\dependencies\__init__.py", line 76, in __call__     return await self.call(**values)   File "c:\programdata\miniconda3\lib\site-packages\nonebot_plugin_word_bank2\__init__.py", line 53, in handle_wb     await wb.parse_msg(   File "c:\programdata\miniconda3\lib\site-packages\nonebot_plugin_word_bank2\data_source.py", line 226, in parse_msg     return Message.template(msg).format(*file_list, **at, **kwargs)   File "c:\programdata\miniconda3\lib\site-packages\nonebot\adapters\_template.py", line 80, in format     msg += self.vformat(self.template, args, kwargs)   File "c:\programdata\miniconda3\lib\site-packages\nonebot\adapters\_template.py", line 94, in vformat     result, _ = self._vformat(format_string, args, kwargs, used_args, 2)   File "c:\programdata\miniconda3\lib\site-packages\nonebot\adapters\_template.py", line 165, in _vformat     formatted_text = self.format_field(obj, str(format_control))   File "c:\programdata\miniconda3\lib\site-packages\nonebot\adapters\_template.py", line 181, in format_field     super().format_field(value, format_spec)   File "c:\programdata\miniconda3\lib\string.py", line 235, in format_field     return format(value, format_spec) TypeError: unsupported format string passed to bytes.__format__  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BalconyJH** [comment]
已经更改并重启nb但似乎未生效
